Update paper-size in custom template
When using the `custom-theme.typ` there was compilation errors with `paper: paper-size`.
```
[08:32:31] compiled with errors
error: unknown variable: paper-size
    ┌─ custom-theme.typ:125:11
    │
125 │     paper: paper-size,
    │            ^^^^^^^^^^
```
It is updated to reflect to the other templates.